### ISSUE TITLE
Cache collisions with keys that have a . (period)

### ISSUE THREAD

**Issue by nick-randal** [acarteas/FileCache#13]
fileCache["A.1"] = 12;
fileCache["A.2"] = "Bob";

Both A.1 and A.2 are now "Bob".

I can see that the cache filename is "A.dat" so the cache value is being shared with anything that is A.*

I think the problem is on line 834 of FileCache.cs here:
string filePath = Path.Combine(directory, Path.GetFileNameWithoutExtension(FileName) + ".dat");

should Path.GetFileNameWithoutExtension(FileName) be used here?

**Comment by acarteas** [comment]
I'm guessing it has to do with file system limitations.  I'll take a look
just to be sure.  I had planed on rewriting that part of the code sometime
this summer anyway so thanks for the additional motivation.

**Comment by nick-randal** [comment]
Submitted a PR. Unless I overlooked something, it looks like a simple fix.

**Comment by acarteas** [comment]
Issue addressed with release of v3.0.1
