### ISSUE TITLE
colon in cache key causes issue

### ISSUE THREAD

**Issue by scottbrenneman** [acarteas/FileCache#16]
If I use a colon (:) in my cache key, it looks like the characters before the colon are stripped from the cache entry.

For example, if I use "foo:bar" as the cache key, the key will end up being "bar".

It's not significant problem (I just refrain from using a colon now), but it's worth pointing out.

**Comment by acarteas** [comment]
Yes, this is because FC uses the key name as the file name and you can't
use colons in file names.  I'm working on a replacement system that will
address this issue.  Thanks for providing more motivation!

**Comment by ndrwrbgs** [comment]
@acarteas any update on this effort you were making?

In an implementation I was working on (before finding this library and wanting to not duplicate) I implemented like `Dictionary` (stored keys by hash, then a 'list' structure by using guid + an 'actualKey' file).

**Comment by acarteas** [comment]
Yes, branch release/3.0.0 offers hash-based file caching as an option, which should address the issue.  However, it's lacking some of the bug fixes introduced in the master branch.  This, plus lack of field testing on my part has prevented me from pulling it into the main branch.

**Comment by ndrwrbgs** [comment]
Is there anything I can do to help out? I'm cautious to take a fork and depend on that for fear of missing new releases, I think it'd be better use of my time to help with merging or validation.

**Comment by ndrwrbgs** [comment]
@acarteas I merged release3.0.0 with the existing changes on master:
https://github.com/ndrwrbgs/FileCache/tree/ndrwrbgs/release3

I think there are some race conditions and possible bugs in the Hash version, but the interfaces would enable me to plug in my own version anyway. I'd be happy to review the code in depth if we're going to move forward with these changes, just let me know!

**Comment by acarteas** [comment]
Ya, that sounds good.  I'll pull down your code and take a look and make a PR into the master branch if everything looks good.

**Comment by acarteas** [comment]
Looks good.  Thanks for your help.  I'll make a PR soon.

**Comment by acarteas** [comment]
Closing as new v3.0 is pushed to master branch.  I'm thinking it would be better to start new github issues related to specific components of the new release.
