### ISSUE TITLE
Method Get() with regionName creates/overwrites cache file (.dat) in the wrong location?

### ISSUE THREAD

**Issue by mzamorski** [acarteas/FileCache#2]
Suppose I have some value (the key is "my_key") in the cache with region name "my_region", so the directory structure looks like this:

..\cache\my_region\my_key.dat

When I call method `cache.Get("my_key", "my_region")` file appears in (wrong?) location:

..\cache\my_key.dat

It's confusing and I think it's a bug.

Test code here:

```
var cache = new FileCache();
var policy = new CacheItemPolicy { SlidingExpiration = new TimeSpan(0, 5, 0) };

var key = "my_key";
var region = "my_region";
object value = null;

cache.Add(key, "foo", policy, region);
cache.Add(key, "bar", policy);

value = cache.Get(key); // returns: "bar"
value = cache.Get(key, region); // returns: "foo"
value = cache.Get(key); // returns: "foo" ?!

```

**Comment by acarteas** [comment]
Thanks,

Yes, this appears to be a bug.  I will try to get this fixed soon.

--Adam

**Comment by acarteas** [comment]
This should be fixed.  With a sliding expiration date, FC did a payload writeback but failed to send over region info, which resulted in saving to the default region.  A tricky bug to find.  Thanks for the tip.
