### ISSUE TITLE
Expired items or over-the-limit cache are not cleared when using region names

### ISSUE THREAD

**Issue by sergeystoma** [acarteas/FileCache#25]
It appears that when using region names the automatic items cleanup doesn't work as expected, neither removing expired when specifying cleanup interval, nor the whole cache cleanup when the total cache size gets over the limit.

The reason is that in both cases the automatic cleanup is triggered with `regionName == null`. As the result, `FileCache.GetKeys` (2.2.0 series) or `CacheManager.GetKeys` (3.0) return cached item keys only in the root region, ignoring everything else.

Not sure if that's by design, and if there is a different way of setting this up. In my local version, I've hacked the GetKeys method to iterate over all subdirectories and return pairs of file name + region (`IEnumerable<Tuple<string, string>> GetKeys`).

**Comment by acarteas** [comment]
Sorry, just saw this.  Github didn't notify me of your message.  I guess FC would have to track active regions and then perform a sweep on everything on the appropriate trigger.  Care to give it a whack?

**Comment by acarteas** [comment]
closing as this got integrated into the main branch some time ago.
