### ISSUE TITLE
I have FileCache.Get IOException

### ISSUE THREAD

**Issue by pochunyu** [acarteas/FileCache#3]
I have FileCache.Get IOException
[IOException: The process cannot access the file because it is being used by another process]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +216
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +736
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) +63
   System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle) +38
   System.IO.File.SetLastAccessTimeUtc(String path, DateTime lastAccessTimeUtc) +41
   System.Runtime.Caching.FileCache.Get(String key, String regionName) +768
   System.Runtime.Caching.FileCache.get_Item(String key) +13

Could add FileShare.ReadWrite?
private FileStream GetStream(string path, FileMode mode, FileAccess access, bool lockfile = false)
        {
            FileStream stream = null;
            TimeSpan interval = new TimeSpan(0, 0, 0, 0, 50);
            TimeSpan totalTime = new TimeSpan();
            while (stream == null)
            {
                try
                {
                    if (lockfile)
                        stream = File.Open(path, mode, access, FileShare.None);
                    else
                        //stream = File.Open(path, mode, access);                        
                        **stream = File.Open(path, mode, access, FileShare.ReadWrite);**
                }

**Comment by acarteas** [comment]
I will try to look into this soon.  Sorry for the long response.

**Comment by pochunyu** [comment]
web user read cache data at the same time.

**Comment by acarteas** [comment]
You're change seems reasonable.  I have implemented it in the latest commit.
