### ISSUE TITLE
Flush does not account for regions when getting keys, throws exceptions

### ISSUE THREAD

**Issue by CelerityChip** [acarteas/FileCache#32]
The Flush method does not pass in the region name to the GetKeys method, and thus always only gets the keys for the root region.  This causes a couple of issues:

1) If you call Flush with a regionName, it will attempt to flush keys from the root region instead, but will crash if it finds any because it uses the wrong directory name.
2) If you call Flush without a regionName, it will flush only the root region, and not the child regions as it should.

The solution is to enumerate over all of the regions, including the root region, calling GetKeys and the subsequent foreach loop on each region name.  I have corrected code with unit tests which I will submit a PR for.

**Comment by acarteas** [comment]
Cool.  Do you think this will also address #25?

**Comment by CelerityChip** [comment]
No, but they're definitely related.  The fix to CleanCache() would be almost identical; DeleteOldestFiles() is a tad more complicated but similar.  If you'd please grant me contributor rights, I'll get you a PR to cover all four scenarios and in a more consistent fashion.

**Comment by acarteas** [comment]
It is my understanding that the more typical route is fork -> commit/push -> PR.

**Comment by CelerityChip** [comment]
Ah ok, will do!

**Comment by CelerityChip** [comment]
PR is all ready for your review.

**Comment by acarteas** [comment]
See comments on PR #33

**Comment by acarteas** [comment]
Closing issue as PR is now in main branch.
