### ISSUE TITLE
[Enhancement] Detect and warn user when `Hashed` is used, `string` is the key, and the new .net randomized hashes are in use

### ISSUE THREAD

**Issue by ndrwrbgs** [acarteas/FileCache#35]
Otherwise the cache is only valid for a single execution

**Comment by ndrwrbgs** [comment]
It _appears_ (not an expert) that `AppDomain.CurrentDomain.IsCompatibilitySwitchSet("UseRandomizedStringHashAlgorithm")` returns `false` for net45, net48, etc, netstandard2.0, but `null` for netcoreapp2.0, so we might be able to call that and check for `!= false` (since it seems `null` AND/OR `false` means "off")

**Comment by ndrwrbgs** [comment]
Alternatively we would implement our own stable hash, but that would be prone to the DoS attacks that prompted .NET to implement randomized hashes at all, hence the suggestion to just 'warn' when they're in use (as some use case may not even INTEND to cache beyond single-process-execution).

**Comment by acarteas** [comment]
Versions greater than 3.1.0 now use xxHash, which addresses this issue's concerns.
