### ISSUE TITLE
Duplicate policy being entered on Sliding expiration mdoe

### ISSUE THREAD

**Issue by ndrwrbgs** [acarteas/FileCache#37]
![image](https://user-images.githubusercontent.com/10776890/70871125-9e2fd100-1f50-11ea-8c09-97385d39ba2c.png)

I think that this 'cachePath' was supposed to be key again

**Comment by ndrwrbgs** [comment]
Not a problem for BasicFileCacheManager since it ALWAYS passes the input through Path.GetFileNameWIthoutExtension (so passing a full path would be akin to passing just the key)

**Comment by ndrwrbgs** [comment]
"Duplicate policy being entered" meaning there becomes 2 policy files for the same cache item

**Comment by acarteas** [comment]
That code is in Get on line 816 of FileCache.cs, right?  If so, line 819 sends the raw key to the cache manager which then constructs an appropriate file name for that key (either file path or hashed value).  That value (cachedItemPath) is then sent to the WriteHelper function.  This seems correct to me, or am I thinking about it incorrectly?

**Comment by ndrwrbgs** [comment]
I think that it's not constructing the value you'd want. The symptom I was seeing (working backward, bear with me) was exceptions being caught (and swallowed) about missing file. Tracing this back, it appeared there was a file in the policy directory that had no matching file in the contents directory. I was only ever adding (and expiring) 1 key, so I was confused. Upon tracing, I found that in one case, the key itself was being given to the policy hash function, but in another case a path to the contents file was being given.

I think that in the 'Basic' mode, this is fine since there is the mentioned 'Path.GetFileNameWithoutExtension' but in Hashed mode that file name is not the key (so it gets the HASH of the key, and re-hashes it).

**Comment by ndrwrbgs** [comment]
specifically I think the fix is that they 'key' in this case needs to be the actual key, rather than 'cachePath' (but I haven't in-depth read the surrounding code for a week so I'd want to lean on tests :-P)

The picture was from R# decompiling the code, I think it's this line (though variable names have changed, so perhaps a commit has been made since the release I have)
https://github.com/acarteas/FileCache/blob/ea39af833f66310492b3adb0a5ac6f9a24d744e7/src/FileCache/FileCache.cs#L853

**Comment by acarteas** [comment]
Ah okay that makes sense. Sounds like I need to do an inspection of the code. I'm on vacation right now so I probably won't be able to do an inspection of the code until after Jan 1.
