### ISSUE TITLE
Files not cleaned up after cleanInterval?

### ISSUE THREAD

**Issue by zijianhuang** [acarteas/FileCache#4]
`Cache = new FileCache(path, false, TimeSpan.FromMinutes(2);`

I have the Slidingexpiration to 1 minutes, and the clearInterval to 2 minutes. The expiration of the cache is working well, however, the files are not deleted after 2 minutes.

I use FileCache inside a singleton class. I have this design because previously I was using MemoryCache which is a singleton. I noticed that after I run the application again and the constructor of FileCache is called, the older files are deleted.

Question 1: Is it intentional to remove old caches according to cleanInterval when the constructor is called? So singleton is not recommended?

Question 2: Is there an option to remove a cached file when the cache is expired?

**Comment by acarteas** [comment]
Thanks for your questions.  Regarding your questions:

I use a singleton pattern on FC so I believe that this should be okay.  Regarding deleting expired items on instantiate (question 1), would you not expect this occur?

For question 2, it sounds like you're running FC in a persistent application?  Right now, items are deleted on a call to CleanCacheAsync().  However, as this might be a rather expensive operation I/O wise, we were a bit hesitant to have this occur automatically during regular intervals as this might unexpectedly slow down an application.  That being said, in your situation, it might be a nice feature to have a timer call a delete for a particular cache item when an item has expired.  As we wrote this code for a non-persistent application (web), this feature was of no use to us, but I can see it being very handy in a persistent application.

**Comment by zijianhuang** [comment]
thanks for the clarification. I used it in a Web app. I just change the logic now. Just create a FC instance everytime I need to access the file cache in App_Data. So far so good. Singleton is more relevant to MemoryCache. Since files are persisted in disk, singleton may not bring benefit.
