### ISSUE TITLE
NullReferenceException in ShouldClean method

### ISSUE THREAD

**Issue by Ericvf** [acarteas/FileCache#42]
The `FileCache.Init( ... )` method calls the `ShouldClean` method before initializing the `CacheManager` class member. 

To mitigate the exception, consider moving the initialization of the `CacheManager` to be called before `ShouldClean` is called. Alternatively you may also use the null-conditional operator in the `ShouldClean` method to prevent the `NullReferenceException` from being thrown.

**Comment by huangmux** [comment]
ding

**Comment by acarteas** [comment]
I'm sorry, I'm not getting notifications for some reason.  This looks simple and reasonable.  Can you do the work and submit a PR?

**Comment by acarteas** [comment]
Implemented in FC version >= 3.2.0
