### ISSUE TITLE
.NET Standard Version

### ISSUE THREAD

**Issue by maldworth** [acarteas/FileCache#5]
Would you be willing to accept a PR for .NET Standard/Fullframework version of this project? This way you could offer a nuget package for .net standard in addition to the 4.0 and 4.5 frameworks.

**Comment by acarteas** [comment]
Yes, that would be great.  I've been thinking of doing an update to make
this project cross platform compatible.

**Comment by maldworth** [comment]
Great, I'll take a go at this.

Also, have you ever considered allowing a different serialization into the cached .dat files? Newtonsoft Json perhaps? Because that ObjectBinder() looks like it's good for poco objects in the current assembly, but what if I might be serializing some objects that are in a few different referenced dlls?

I know this would require another dependency (on newtonsoft), so it definitely could be something the user could opt in for in an additional dll/dependency.

**Comment by acarteas** [comment]
I've used Newtonsoft Json in various .NET MVC projects but I'm unaware of
how it might be more generalizable when compared to binary serialization.
Do you have a link on the subject and/or can you explain it to me?

Furthermore, isn't string-based deserialization (JSON) quite a bit slower
than binary?  That being said, I can see how JSON-based serialization might
be more appropriate when the library is used in certain web contexts.

I agree with your assessment that requiring additional binaries might be
off putting to those that want a simple library and that an op-tin approach
would be most appropriate.

**Comment by maldworth** [comment]
Yep there would be a performance hit. I'm just thinking for the scenario when I can't add the [Serializable] attribute to the poco which is in an assembly I don't own. So I'd like an alternative for those use cases. But this could be a future addition I will probably add, but make it opt-in of course. For now .net standard support is my goal :).

**Comment by maldworth** [comment]
Few more questions:

Should I do some namespace cleanup here?

1. I notice the main FileCache belongs to `namespace System.Runtime.Caching` which is good,
2. but then some of the unit tests are `namespace FC.UnitTests`
3. and some of the file cache binder are `namespace Codeplex.FileCache`

Please let me know what namespace I should consolidate 2 and 3 to...

Also I'm thinking of dropping the Example console application. The Readme.md has examples and the unit tests cover anything that might not be mentioned in documentation, so this will make it a bit more clean.
